# Generated by Django 4.1.6 on 2023-02-04 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Zhyldyzbek', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheeps',
            name='zagon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zagon', to='Zhyldyzbek.zagons'),
        ),
    ]
