# Generated by Django 4.1.6 on 2023-02-04 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Zhyldyzbek', '0002_alter_sheeps_zagon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheeps',
            name='zagon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='del_zagonsheeps', to='Zhyldyzbek.zagons'),
        ),
        migrations.CreateModel(
            name='Deleted_sheeps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Sheeps')),
                ('zagon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zagonsheeps', to='Zhyldyzbek.zagons')),
            ],
        ),
    ]
